### PR TITLE
added to the icon library

### PR DESCRIPTION
**Pull request by misspee007**
I added to the icon library. I didn't notice any sizing restrictions besides the 1:1 aspect ratio, I hope these icons are alright.

PS: I'm contributing for hacktoberfest.

### CODE REVIEW

**Comment by RobTheFiveNine** [comment]
Thanks for the additions! There's just two things to address though:

1. The `package-lock.json` file needs removing. The primary package manager for the project is `yarrn`, having two lock files will make it more difficult to maintain.
2. If possible, can you use an opaque image for `GASS`? The one submitted has a transparent background, rather than a solid one (I should have mentioned that requirement in the notes, will add that shortly).

**Comment by misspee007** [comment]
Alright, l’ll look into it asap.

**Comment by misspee007** [comment]
All done! @RobTheFiveNine

**Comment by RobTheFiveNine** [comment]
> All done! @RobTheFiveNine

Looks good, merging now! Happy Haccktoberfest 🎉

**Comment by misspee007** [comment]
Thanks and happy hacktoberfest!

**Pull request merged**
