### PR TITLE
adding computershare logo to library

### PR DESCRIPTION
**Pull request by bruceyboy86**
Happy hacktoberfest!

### CODE REVIEW

**Comment by RobTheFiveNine** [comment]
Thanks for the addition - could you change the icon to be one with an opaque background though? I forgot to add about opaque backgrounds to the contribution notes, but added now :)

**Comment by bruceyboy86** [comment]
Sure, I'll get on it :)

**Comment by bruceyboy86** [comment]
I've checked and the image already has a transparent background. Happy hacktoberfest :)

**Comment by RobTheFiveNine** [comment]
> I've checked and the image already has a transparent background. Happy hacktoberfest :)

I think you may have misread the last message - it should be opaque rather than transparent :)

**Pull request merged**
